apiVersion: v1
kind: ConfigMap
metadata:
  name: dc-webapp-conf
  namespace: databuff
  labels:
    app: dc-webapp-executor
data:
  webapp.yml: |
    server:
      port: 18080

    zuul:
      ignoredServices: '*'
      routes:
        api:
          path: /graphql
          serviceId: collector
        login:
          path: /login/account
          serviceId: collector

    collector:
      path: /graphql
      ribbon:
        # Point to all backend's restHost:restPort, split by ,
        listOfServers: 127.0.0.1:12800

    spring:
      jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
      datasource:
        name: Databuff
        url: jdbc:mysql://mysql-svc:3306/dc_databuff?useSSL=false&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai
        username: root
        password: 234*(sdlj12
        # 使用Druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        druid:
          filters: stat
          maxActive: 20
          initialSize: 1
          maxWait: 60000
          minIdle: 1
          timeBetweenEvictionRunsMillis: 60000
          minEvictableIdleTimeMillis: 300000
          validationQuery: select 'x'
          testWhileIdle: true
          testOnBorrow: false
          testOnReturn: false
          poolPreparedStatements: true
          maxOpenPreparedStatements: 20
        # redis
      redis:
        host: redis-svc
        port: 6379
        timeout: 10000
        password: Databuff@123
        jedis:
          pool:
            max-idle: 8
            min-idle: 0
            max-wait: -1
            max-active: 200
      resources:
        add-mappings: false
      mvc:
        throw-exception-if-no-handler-found: true
      ### xxl-job, email
      mail:
        host:
        port:
        username:
        from:
        password:
        properties:
          mail:
            smtp:
              auth:
              starttls:
                enable:
                required:
              socketFactory:
                class:

      # 使用aop操作日志
      aop:
        auto: true
        proxy-target-class: true

      application:
        name: nacos-config-client
        cloud:
          nacos:
            discovery:
              server-addr: http://192.168.50.106:8848
              file-extension: yaml
              namespace: 72008218-19b0-4960-ab44-a0cbdd8097a0
              username: nacos
              password: nacos
          config:
            username: nacos
            password: nacos
            contextPath: /nacos
          discovery:
            username: nacos
            password: nacos

    mybatis:
      # Mybatis配置Mapper路径
      mapper-locations: classpath:mapper/*.xml
      configuration:
        map-underscore-to-camel-case: true
      # Mybatis配置Model类对应
      type-aliases-package: com.databuff.webapp.admin.model

    pagehelper:
      params: count=countSql
      # 指定分页插件使用哪种方言
      helper-dialect: mysql
      # 分页合理化参数 pageNum<=0时会查询第一页 pageNum>pages(超过总数时) 会查询最后一页
      reasonable: 'true'
      support-methods-arguments: 'true'

    mapper:
      # 通用Mapper的insertSelective和updateByPrimaryKeySelective中是否判断字符串类型!=''
      not-empty: true

    #日志级别从低到高分为TRACE < DEBUG < INFO < WARN < ERROR < FATAL，如果设置为WARN，则低于WARN的信息都不会输出
    logging:
      config: classpath:logback-spring.xml
      path: /usr/local/log
      # Debug打印SQL
      level.com.dacheng.common.mapper: info

    swagger:
      enable: true
    jasypt:
      encryptor:
        password: 123456   #开发环境密码

    management:
      # Customizing the management endpoint paths
      context-path: /manage
      ### actuator
      server:
        servlet:
          context-path: /actuator
      health:
        mail:
          enabled: false

    # elastic
    ES:
      cluster_name: databuff-es-cluster
      hosts: elasticsearch-svc:9200
      port: 9200
      user: elastic
      password: Databuff@123
      poolsize: 6
      #索引前缀
      indexPrefix: dc_
      #保存天数
      expireDays: 7
      max-total: 30
      min-idle: 3
      max-wait-millis: 5000
      soft-min-evictable-idle-time-millis: 300000
      test-on-borrow: true
    
    influx:
      url: http://influxdb-svc:8086
      user: admin
      password: 234*(sdlj12
      max-total: 30
      min-idle: 3
      max-wait-millis: 5000
      soft-min-evictable-idle-time-millis: 300000
      test-on-borrow: true

    kafka:
      ip: dc-kafka-svc:9092

    #版本
    version: "DataBuff|v2.0"
    #渠道: 官方000
    channel: "000"
    # logo路径
    logoPath:
    # 二维码地址
    qrUrl: http://databuff.com:7300

    # AccessToken过期时间-5分钟-5*60(秒为单位)
    accessTokenExpireTime: 30240000
    # RefreshToken过期时间-30分钟-30*60(秒为单位)
    refreshTokenExpireTime: 3600
    # dczw缓存过期时间-5分钟-5*60(秒为单位)(一般设置与AccessToken过期时间一致)
    shiroCacheExpireTime: 3600

    # 云通信短信API
    sms:
      accessKeyId:
      accessKeySecret:
      regionId:
      signName:
      templateCode:
      enable: false
    # 邮件发件人API
    mail:
      addr:
      user: DataBuff
      password:
      enable: false
      smtp:
        host: smtp.dacheng-tech.com
        port: 25
        ssl: false
      ### xxl-job, access token
    xxl:
      job:
        accessToken: default_token
        ### xxl-job, i18n (default is zh_CN, and you can choose "zh_CN", "zh_TC" and "en")
        i18n: zh_CN
        ## xxl-job, triggerpool max size
        triggerpool:
          fast:
            max: 20
          slow:
            max: 10
        ### xxl-job, log retention days
        logretentiondays: 5