---
apiVersion: v1
kind: Service
metadata:
  name: dc-kafka-svc
  namespace: databuff
  labels:
    app: dc-kafka
spec:
  ports:
    - port: 9092
      name: server
  clusterIP: None
  selector:
    app: dc-kafka