apiVersion: v1
kind: ConfigMap
metadata:
  name: dc-redis-conf
  namespace: databuff
  labels:
    app: dc-redis
data:
  redis.conf: |
    bind 0.0.0.0
    protected-mode no
    port 6379
    daemonize no
    pidfile /var/run/redis_6379.pid
    databases 16
    save 900 1
    save 300 10
    save 60 10000
    dir /data
    requirepass Databuff@123
