apiVersion: v1
kind: PersistentVolume
metadata:
  name: dc-redis-pv
  labels:
    pv: dc-redis-pv
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 5Gi
  storageClassName: nfs
  nfs:
    path: /data/nfs/databuff-kaifa/dc-redis-data
    server: 192.168.50.126 # nfs服务器ip
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dc-redis-pvc
  namespace: databuff
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  selector:
    matchLabels:
      pv: dc-redis-pv
  resources:
    requests:
      storage: 5Gi

